### ISSUE TITLE
fix(rust): check `git` based dependencies for new releases

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#1840]
For some Rust dependencies it has been necessary to specify git repositories because the repository has fixes and/or features that are not yet available in the latest release. These should be checked periodically for a new release (Renovate won't notify of this). At the time of writing theses are:

```toml
pulldown-cmark = { git = "https://github.com/raphlinus/pulldown-cmark", rev = "61cc1ba16d9ac0d95babafccbb2ed5754dd80ea8" }
anthropic = { git = "https://github.com/abdelhamidbakhta/anthropic-rs.git", rev="c3d48caad57a26dbcbe37c63299a451cc1cc7254"}
```
