### ISSUE TITLE
bug(jsonld): decode is broken by `AuthorRole` nodes 

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#1971]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

There is something about `AuthorRole` nodes that breaks the decoding of JSON-LD. I've had to skip tests by adding this to `config.yaml` files in places:

```yaml
# TODO: Fix issues decoding AuthorRole with JSON-LD (?)
compact.jsonld:
  decode:
    skip: true
jsonld:
  decode:
    skip: true

```

### Reproduction steps

Remove the above skips and run:

```console
cargo test -p codecs examples
```
