### ISSUE TITLE
fix(node execution): strip `PromptBlock.content` before setting on `InstructionBLock`

### ISSUE THREAD

**Issue by nokome** [stencila/stencila#2328]
Recently we added  a `promptProvided` property to instructions:

https://github.com/stencila/stencila/blob/acfc61dafbc7ecc7bd8b63c9a51c5a8deae52e66/schema/Instruction.yaml#L64-L72

The prompt matches/specified for the instruction gets executed and its content stored in this property (see example below from 
running `cargo run -p cli execute temp.smd --to yaml`). Storing the prompt like this is useful for lots of things, not least being able to show the user the system prompt sent (as a structured document! and may be in the future modify parts of it). 

```yaml
type: Article
authors: []
provenance:
- type: ProvenanceCount
  provenanceCategory: Hw
  characterCount: 37
  characterPercent: 24
- type: ProvenanceCount
  provenanceCategory: Mw
  characterCount: 120
  characterPercent: 76
content:
- type: InstructionBlock
  instructionType: New
<SNIP>
  promptProvided:
    type: PromptBlock
    prompt: stencila/new/paragraph
    content:
    - type: Heading
      level: 1
      content:
      - type: Text
        value:
          string: Instructions
    - type: Paragraph
      content:
      - type: Text
        value:
          string: You are an assistant helping to write a Markdown document. Your task is to write a single paragraph.
    - type: Paragraph
      content:
      - type: Text
        value:
          string: Pay attention to the context of the current position in the document and follow any section guidelines.
    - type: Paragraph
      content:
      - type: Text
        value:
          string: Pay attention to the previous and next paragraphs (if any) and use them to help infer the intent of the user's instruction.
    - type: Paragraph
      content:
      - type: Text
        value:
          string: Only provide ONE paragraph. Do NOT provide any comments or explanation.
    - type: Heading
      level: 1
      content:
      - type: Text
        value:
          string: Context
    - type: IncludeBlock
      source: ../partials/context/document/metadata.smd
      content:
      - type: IfBlock
        clauses:
        - type: IfBlockClause
          code:
            string: document.metadata.properties.length > 0
          isActive: false
          content:
          - type: Heading
            level: 2
            content:
            - type: Text
              value:
                string: Document metadata
          - type: Paragraph
            content:
            - type: Text
              value:
                string: 'An overview of the document''s metadata follows. Use this information to guide the style and subject matter:'
```

But there is a lot of unnecessary detail in the executed prompt such as inactive `IfBlockClause`s and execution details. We should add an `Inactive` strip scope here

https://github.com/stencila/stencila/blob/acfc61dafbc7ecc7bd8b63c9a51c5a8deae52e66/rust/node-strip/src/lib.rs#L21-L24

 and then strip the prompt content using `Inactive`, `Execution`, `Timestamps` and maybe some of the other scopes **before** it is set on the instruction.
