### ISSUE TITLE
Document the document and block options

### ISSUE THREAD

**Issue by edwardabraham** [stencila/stencila#2395]
What are the options available to control the document? I am used to using Quarto, which has a very long list of document level options (e.g, https://quarto.org/docs/reference/formats/pdf.html).  As an example of what this looks like in practice,  I have copied below the YAML header from an test of using Quarto to generate reports for use at Dragonfly.

Similarly, in Quarto, execution blocks have a wide range of options (https://quarto.org/docs/computations/execution-options.html)

This is an illustration of the full scope. The particular issue I ran into immediately, which is much simpler, was wanting to control the height of figures in the output. The aspect ratio was too 'square', and I wanted t tweak it. How would I do that? I cant find any documentation on this for SMD files. 

```
---
title: Overlap of the distribution of black petrel (*Procellaria parkinsoni*) with  New Zealand trawl and longline fisheries - Quarto version
shorttitle: "Black petrel overlap with trawl and longline fisheries"
subtitle: "A report for testing purposes"
author:
  - "John A. G. Smith"
  - "Jane E. Smith"
  - "Andrew Smith"
reportyear: "`r format(Sys.Date(), '%Y')`"
reportmonth: "`r format(Sys.Date(), '%B')`"
imagecover: cover.jpg
imagesource: https://www.flickr.com/photos/naoc0804/13923065676/in/explore-2014-04-20
bibliography: test.bib
execute:
  echo: false
  keep-md: true
format:
  pdf:
    pdf-engine: xelatex
    latex-auto-install: true
    template: dragonfly-report-quarto-template.tex
    keep-tex: true
    include-in-header:
      - text: |
          \usepackage{lipsum}
    cite-method: biblatex
    biblatexoptions:
      - "backend=biber"
  docx: default
  html:
    theme: lumen
    self-contained: true
  revealjs:
    theme: league
    output-file: dragonfly-presentation.html
    slide-number: true
    chalkboard: false
    preview-links: false
    code-fold: true
    toc: false
    toc-depth: 1
    mouse-wheel: true
    transition: fade
    footer: Antipodean albatross projects
    self-contained: true
---
```
