### ISSUE TITLE
feat(ghost): `docker-compoes.yml` for Ghost theme testing

### ISSUE THREAD

**Issue by jduckles** [stencila/stencila#2547]
### Which component?

Other

### What's your idea?

Add a docker file for testing... Ghost tends to want a `url=` DNS entry specified, so we'll have to figure out how that works on localhost etc. 

```
version: "3.1"
services:
  ghost:
    image: ghost:latest
    restart: always
    volumes:
      - ./blog:/var/lib/ghost/content
    ports:
      - 9989:2368
    environment:
      - url=https://stencila.DOMAIN.tld
      - database__client=sqlite3
      - database__connection__filename=/var/lib/ghost/content/data/ghost.db
```
