### ISSUE TITLE
docs(ghost): Discussion of documenting using stencila docs

### ISSUE THREAD

**Issue by jduckles** [stencila/stencila#2557]
### Which component?

Stencila CLI

### What do you think needs to be improved?

I'd like to work through how to best bring documentation `.md` and `.smd` files from the `stencila/stencila` repo over to the website repo for pushing to Ghost. In conversations at the standup we talked about using documentation's source raw urls in the `stencila/stencila` repo, or wherever they may be as the authoritative version of the files. These often don't have yaml metadata, and any that we would add would get clobbered by automated tools that generate the files such as CLAP. Hence the approach I've proposed below.

I've been playing around with a small script (in Python) that would let us drop just a yaml file (in Stencila yaml header format) and one more key `source:`. Like this:

```
config:
  publish:
    ghost:
      slug: reference-cli
      tags:
      - Reference
      - '#docs'
      type: post
source: https://raw.githubusercontent.com/stencila/stencila/refs/heads/main/docs/reference/cli.md
```

We could have these in the `stencila/website` repo and iterate over them with `stencila publish ghost` to push updataes to ghost. In the process we'll download the raw text from `source:`, merge it with the yaml headers and push to Ghost. 

Process to create a new documentation page on the Ghost website would thus be: 

1. Create yaml file in website repo, set `source:` to source documents url
2. fill in the config -> publish -> ghost KVs appropriate for that documentation
3. merge yaml and documentation (based on curling / wgeting `source:`)
4. publish to ghost

Its probably best if step 3 never drops the files where the user can see them, as it can cause confusion around which set of yaml headers to update to change / fix things. 

Two questions: 

1. Would it be worth adding this in as a flag to `stencila publish` or is it niche enough we should keep it as its own tooling?
2. Does this seem like a reasonable approach @nokome and @timClicks?
